spring:
  application:
    name: provider-test

server:
  port: 10214

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10200/eureka/
    instance:
      prefer-ip-address: true
